add_newline = true
format = "$directory(\n$all)"

[directory]
truncation_length = 100
truncate_to_repo = false
truncation_symbol = "…/"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[✗](bold red)"

[cmd_duration]
min_time = 10_000
format = "[$duration]($style)"

[git_branch]
format = "[$symbol$branch]($style) "

[username]
style_user = "bold white"

